services:

  ugc2:
    build: ugc2/app
    env_file:
      - ./.env
    restart: unless-stopped
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/8000"
      interval: 5s
      timeout: 3s
      retries: 20
    ports: []
