services:
  postgres:
    image: postgres:13.10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./research/pg_init.sql:/docker-entrypoint-initdb.d/init.sql
    user: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

volumes:
  postgres_data:
