name: UGC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linter:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@master

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ugc2/app/requirements_ci.txt -r ugc2/app/requirements

    - name: Check sort imports with isort
      run: |
        isort --check-only ugc2

    - name: Check with Flake8
      run: |
        flake8 --exit-zero ugc2

    - name: Check with mypy
      run: |
        cd ugc2/app && mypy --explicit-package-bases .
